Add newrelic extension for php 7.4 to 8.1
shivammathur/homebrew-extensions pull request #2433
Opened 2023-01-13 16:27 UTC by DracoBlue

---
name: 🎉 Add newrelic extension
about: For a project we need newrelic also available locally
labels: enhancement

---

### Description

It adds the newrelic.so extension for php 7.4 till 8.1 (the 8.2 is not available, yet). As newrelic requires a deamon available, it will create a socket for each version suffixed with the version (e.g. `/tmp/.newrelic80.sock`).

2023-01-13 16:44 UTC, DracoBlue commented
Hello @shivammathur,

I am not sure if the build-formula or get-matrix commands fail because of my lack of contributor rights or not. Thus I leave it in this state for you to review if I did something wrong.

2023-01-13 16:46 UTC, shivammathur commented
@DracoBlue Please rebase on master

2023-01-13 16:47 UTC, DracoBlue commented
Done! Let's see 👍

2023-01-13 16:56 UTC, DracoBlue commented
Will check results, but I guess I need an approval to run the workflow from your side @shivammathur

2023-01-13 17:56 UTC, DracoBlue commented
@shivammathur I rebased your last commit from 4e0dc961184fdadf258b91edb165a096426abb36, too.

2023-01-13 18:25 UTC, shivammathur commented on Formula/newrelic@7.4.rb
> +  head "https://github.com/newrelic/newrelic-php-agent.git"
```diff
- head "https://github.com/newrelic/newrelic-php-agent.git"
+ head "https://github.com/newrelic/newrelic-php-agent.git", branch: "main"
```

2023-01-13 18:26 UTC, shivammathur commented on Formula/newrelic@8.0.rb
> +  head "https://github.com/newrelic/newrelic-php-agent.git"
```diff
- head "https://github.com/newrelic/newrelic-php-agent.git"
+ head "https://github.com/newrelic/newrelic-php-agent.git", branch: "main"
```

2023-01-13 18:26 UTC, shivammathur commented on Formula/newrelic@8.1.rb
> +  head "https://github.com/newrelic/newrelic-php-agent.git"
```diff
- head "https://github.com/newrelic/newrelic-php-agent.git"
+ head "https://github.com/newrelic/newrelic-php-agent.git", branch: "main"
```

2023-01-13 18:27 UTC, shivammathur requested changes
Please specify the default branch

2023-01-13 19:02 UTC, DracoBlue commented on Formula/newrelic@8.0.rb
> +  head "https://github.com/newrelic/newrelic-php-agent.git"
done.

2023-01-13 19:03 UTC, DracoBlue commented on Formula/newrelic@7.4.rb
> +  head "https://github.com/newrelic/newrelic-php-agent.git"
done

2023-01-13 19:03 UTC, DracoBlue commented on Formula/newrelic@8.1.rb
> +  head "https://github.com/newrelic/newrelic-php-agent.git"
done

2023-01-13 19:05 UTC, DracoBlue commented
Ah good find!

I added branch: "main" everywhere.

2023-01-13 20:51 UTC, shivammathur submitted a review, later dismissed

2023-01-13 20:52 UTC, shivammathur commented
:beers: @BrewTestBot has [triggered a merge](https://github.com/shivammathur/homebrew-extensions/actions/runs/3914836803).

2023-01-13 20:53 UTC, shivammathur commented
:warning: @shivammathur bottle publish [failed](https://github.com/shivammathur/homebrew-extensions/actions/runs/3914836803).

2023-01-13 21:13 UTC, shivammathur commented
:beers: @BrewTestBot has [triggered a merge](https://github.com/shivammathur/homebrew-extensions/actions/runs/3914970413).

2023-01-13 21:15 UTC, merged

2023-01-13 21:21 UTC, shivammathur commented
@DracoBlue 
Thanks for the contribution and the sponsorship.
It should be available now.

2023-01-14 00:20 UTC, DracoBlue commented
Thanks a lot for your work! This tap saves a lot headaches! THANKS!