Newrelic php 8.2 and 8.3
shivammathur/homebrew-extensions pull request #4106
Opened 2024-07-30 17:34 UTC by DracoBlue

---
name: 🎉 New Feature
about: Add newrelic.so also for php8.2 and 8.3
labels: enhancement

---

## A Pull Request should be associated with an Issue.

> If you're fixing a bug, adding a new feature or improving something please provide the details in Issues,
> so that the development can be pointed in the intended direction.

Related issue: 

> Further notes in [Contribution Guidelines](.github/CONTRIBUTING.md)
> Thank you for your contribution.

### Description

This PR adds newrelic for php 8.2 and php 8.3 like I added it for php 8.1 2 years ago at https://github.com/shivammathur/homebrew-extensions/pull/2433 :)

2024-07-30 18:34 UTC, shivammathur requested changes

2024-07-30 18:34 UTC, shivammathur commented on Formula/newrelic@8.2.rb
> +  sha256 "6c27106e8fcd428b1f018fdf7c43513e2a4eb490"
```suggestion
  sha256 "8ffb3d377ec8632a5a873a1a53614b73027c8a3fbebba29c3aba956635578e01"
```

2024-07-30 18:34 UTC, shivammathur commented on Formula/newrelic@8.3.rb
> +  sha256 "6c27106e8fcd428b1f018fdf7c43513e2a4eb490"
```suggestion
  sha256 "8ffb3d377ec8632a5a873a1a53614b73027c8a3fbebba29c3aba956635578e01"
```

2024-07-30 18:39 UTC, DracoBlue commented
I will need to double check if the patches are still missing. I will remove the draft status afterwards.

2024-07-30 21:10 UTC, DracoBlue commented on Formula/newrelic@8.2.rb
> +    inreplace "agent/php_autorum.c", "return (char*)emalloc(len);", "return (char*)emalloc((unsigned)len);"
```suggestion
    inreplace "agent/config.m4", "-l:libprotobuf-c.a", "-lprotobuf-c"
```

2024-07-30 21:10 UTC, DracoBlue commented on Formula/newrelic@8.3.rb
> +    inreplace "agent/php_autorum.c", "return (char*)emalloc(len);", "return (char*)emalloc((unsigned)len);"
```suggestion
    inreplace "agent/config.m4", "-l:libprotobuf-c.a", "-lprotobuf-c"
```

2024-07-31 10:21 UTC, shivammathur commented
:beers: @BrewTestBot has [triggered a merge](https://github.com/shivammathur/homebrew-extensions/actions/runs/10178451463).

2024-07-31 10:23 UTC, merged