feat: add zstd
shivammathur/homebrew-extensions pull request #4159
Opened 2024-08-28 19:28 UTC by shyim

---
name: 🎉 
about: Adding zstd
labels: enhancement

---

### Description

This PR tries to add zstd. But i have no idea how to get some data

2024-08-29 08:53 UTC, shivammathur requested changes

2024-08-29 08:53 UTC, shivammathur commented on Formula/zstd@8.3.rb
> +
Yes, please add formulae for all php versions.

2024-11-04 10:55 UTC, shyim commented
done added all supported php versions and verified locally

2024-11-04 14:41 UTC, merged

2024-11-04 15:52 UTC, shivammathur commented
@shyim Thanks! for the contribution.